<?php
/** @var  \SecommTraining\Secomm\Block\Contentlist $block */
$posts = $block->GetContent();
?>
<div class="container">
    <div class="row">
        <?php if($posts && count($posts)): ?>
        <?php
        foreach ($posts as $data): ?>
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div>
                    <h1><?= $data->getTitle()?></h1>
                </div>
                <div>
                    <a href="/secomm/details/detail/?id=<?= $data->getId() ?>">
                        <img class="img-fluid img-thumbnail" width="300px" src="<?= $block->getImagePath() . $data->getFeatureImage() ?>"/>
                    </a>
                </div>
                <div>
                    <h2><?= $data->getContent() ?></h2>
                </div>
                <div>
                    <?= $data->getUpdate_at() ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="text-right">
        <?php if($block->getPagerHtml()): ?>
            <?php echo $block->getPagerHtml(); ?>
        <?php endif; ?>
        <?php else: ?>
            <div class="rsgitech-no-records">
                <?php echo __('News not available'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
